[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_install = false
experimental = true
lockfile = true
locked = false                                 # aqua backend 等で checksum 未対応のため

[tools]
node = "24.15.0"
pnpm = "10.33.0"
"aqua:go-task/task" = "3.50.0"
"aqua:google/go-jsonnet" = "0.22.0"
